<?php

function d8_angular_blog_demo_theme($existing, $type, $theme, $path) {
    return array(
        'd8_angular_blog_demo' => array(
            'variables' => array(
                'base_href'=>NULL,
                'content' => NULL
            )
        ),
    );
}

function template_preprocess_d8_angular_blog_demo(&$vars){
    $vars['#attached']['library'][] = 'd8_angular_blog_demo/d8_angular_blog_demo';
    $vars['#attached']['drupalSettings']['d8_angular_blog_demo'] = array(
        'module_path'=>drupal_get_path('module', 'd8_angular_blog_demo')
    );
}